export let coinCodes = [
    {"id":"1inch","symbol":"1INCH","name":"1inch"},
    {"id":"ethereum","symbol":"ETH","name":"Ethereum"},
    {"id":"bitcoin","symbol":"BTC","name":"Bitcoin"},
    {"id":"binancecoin","symbol":"BNB","name":"Binance Coin"},
    {"id":"cardano","symbol":"ADA","name":"Cardano"},
    {"id":"solana","symbol":"SOL","name":"Solana"},
    {"id":"dogecoin","symbol":"DOGE","name":"Dogecoin"},
    {"id":"terra-luna","symbol":"LUNA","name":"Terra"},
    {"id":"avalanche-2","symbol":"AVAX","name":"Avalanche"},
    {"id":"polygon","symbol":"MATIC","name":"Polygon"},
    {"id":"terra","symbol":"UST","name":"Terra-UST"},
    {"id":"cosmos","symbol":"ATOM","name":"Cosmos"},
    {"id":"litecoin","symbol":"LTC","name":"Litecoin"},
    {"id":"near","symbol":"NEAR","name":"NEAR-Protocol"},
    {"id":"tron","symbol":"TRX","name":"Tron"},
    {"id":"bitcoincash","symbol":"BCH","name":"Bitcoin-Cash"},
    {"id":"fantom","symbol":"FTM","name":"Fantom"},
    {"id":"stellar","symbol":"XLM","name":"Stellar"},
    {"id":"harmony","symbol":"ONE","name":"Harmony"},
    {"id":"defi-kingdoms","symbol":"JEWEL","name":"DeFi Kingdoms"},
    {"id":"thorchain","symbol":"RUNE","name":"THORChain"},
    {"id":"usd-coin","symbol":"USDC","name":"USD Coin"},
    {"id":"dai","symbol":"DAI","name":"Dai"},
    {"id":"mim","symbol":"SWARM","name":"MIM"},
    {"id":"terrausd","symbol":"UST","name":"TerraUSD"},
    {"id":"tether","symbol":"USDT","name":"Tether"},
    {"id":"ripple","symbol":"XRP","name":"Ripple"},
    {"id":"polkadot","symbol":"DOT","name":"Polkadot"},
    {"id":"shiba-inu","symbol":"SHIB","name":"Shiba Inu"},
    {"id":"chainlink","symbol":"LINK","name":"Chainlink"},
    {"id":"algorand","symbol":"ALGO","name":"Algorand"},
    {"id":"decentraland","symbol":"MANA","name":"Decentraland"},
    {"id":"hedera-hashgraph","symbol":"HBAR","name":"Hedera"},
    {"id":"osmosis","symbol":"OSMO","name":"Osmosis"},
    
     


]