export let coinCodes = [
    {"id":"1inch","symbol":"1INCH","name":"1inch","icon":"/icons/1inch-token.png"},
    {"id":"ethereum","symbol":"ETH","name":"Ethereum","icon":"/icons/ethereum.png"},
    {"id":"bitcoin","symbol":"BTC","name":"Bitcoin","icon":"/icons/bitcoin.png"},
    {"id":"binancecoin","symbol":"BNB","name":"Binance Coin","icon":"/icons/bnb.png"},
    {"id":"cardano","symbol":"ADA","name":"Cardano","icon":"/icons/cardano.png"},
    {"id":"solana","symbol":"SOL","name":"Solana","icon":"/icons/solana.png"},
    {"id":"dogecoin","symbol":"DOGE","name":"Dogecoin","icon":"/icons/dogecoin.png"},
    {"id":"terra-luna","symbol":"LUNA","name":"Terra","icon":"/icons/luna.png"},
    {"id":"avalanche-2","symbol":"AVAX","name":"Avalanche","icon":"/icons/avax.png"},
    {"id":"polygon","symbol":"MATIC","name":"Polygon","icon":"/icons/1inch-token.png"},
    {"id":"terra","symbol":"UST","name":"Terra-UST","icon":"/icons/UST.png"},
    {"id":"cosmos","symbol":"ATOM","name":"Cosmos","icon":"/icons/cosmos.png"},
    {"id":"litecoin","symbol":"LTC","name":"Litecoin","icon":"/icons/litecoin.png"},
    {"id":"near","symbol":"NEAR","name":"NEAR-Protocol","icon":"/icons/near.png"},
    {"id":"tron","symbol":"TRX","name":"Tron","icon":"/icons/tron.png"},
    {"id":"bitcoincash","symbol":"BCH","name":"Bitcoin-Cash","icon":"/icons/1inch-token.png"},
    {"id":"fantom","symbol":"FTM","name":"Fantom","icon":"/icons/fantom.png"},
    {"id":"stellar","symbol":"XLM","name":"Stellar","icon":"/icons/bitcoin.png"},
    {"id":"harmony","symbol":"ONE","name":"Harmony","icon":"/icons/bitcoin.png"},
    {"id":"defi-kingdoms","symbol":"JEWEL","name":"DeFi Kingdoms","icon":"/icons/jewel.png"},
    {"id":"thorchain","symbol":"RUNE","name":"THORChain","icon":"/icons/bitcoin.png"},
    {"id":"usd-coin","symbol":"USDC","name":"USD Coin","icon":"/icons/bitcoin.png"},
    {"id":"dai","symbol":"DAI","name":"Dai","icon":"/icons/bitcoin.png"},
    {"id":"mim","symbol":"SWARM","name":"MIM","icon":"/icons/bitcoin.png"},
    {"id":"terrausd","symbol":"UST","name":"TerraUSD","icon":"/icons/bitcoin.png"},
    {"id":"tether","symbol":"USDT","name":"Tether","icon":"/icons/bitcoin.png"},
    {"id":"ripple","symbol":"XRP","name":"Ripple","icon":"/icons/bitcoin.png"},
    {"id":"polkadot","symbol":"DOT","name":"Polkadot","icon":"/icons/bitcoin.png"},
    {"id":"shiba-inu","symbol":"SHIB","name":"Shiba Inu","icon":"/icons/bitcoin.png"},
    {"id":"chainlink","symbol":"LINK","name":"Chainlink","icon":"/icons/bitcoin.png"},
    {"id":"algorand","symbol":"ALGO","name":"Algorand","icon":"/icons/bitcoin.png"},
    {"id":"decentraland","symbol":"MANA","name":"Decentraland","icon":"/icons/bitcoin.png"},
    {"id":"hedera-hashgraph","symbol":"HBAR","name":"Hedera","icon":"/icons/bitcoin.png"},
    {"id":"osmosis","symbol":"OSMO","name":"Osmosis","icon":"/icons/bitcoin.png"},
    
     


]